15.0 api connector staging
odoo-ps/psus-intern pull request #237
Opened 2022-07-14 20:23 UTC by romf-odoo

### Description

MVP API connector

Link to task: [#2856455](https://www.odoo.com/web#id=2856455&menu_id=4720&cids=17&action=333&active_id=6182&model=project.task&view_type=form)

### All Submissions:

* [ ] My commit respects the [Odoo commit guideline](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#git)
* [ ] My commit message respects the [commit template](https://github.com/odoo-ps/psbe-process/wiki/Commits-message-guidelines#template)
* [ ] I have used pre-commit
* [ ] The PR contains **only** my modification and **no other external** commit

### Sh/Runbot:

* [ ] The commits pass test and the branch is green
* [ ] Unit tests have been implemented / standard ones rewritten
* [ ] The Staging is ISO-Prod and will contain only this dev

### Upgrade:

* [ ] The data affected (*if any*) by the changes has been migrated

2022-07-14 20:54 UTC, tdetry requested changes

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/api.py
> +    _name = 'api'
I would try to find a better name like api.connection

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/api.py
> +class ApiHeaderLines(models.Model):
new file

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +            [('state', '=', 'api_call'), ('id', '=', self.action_server_id.id)])
why??
```
action = self.action_server_id
```

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +        url = action.api_id.url
why not using action.api_id.url directly? same for the headers an payload ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +    def translate_o2m(self, one2many_field):
@api.model ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +                    url, headers=headers, data=local_payload)
I think it would be better to have the request performed and managed on the api class ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +        if api_response.status_code >= 400:
see https://www.geeksforgeeks.org/response-raise_for_status-python-requests/

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +        })
maybe cool to have a generic method to log stuff on the log model ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +                "Something went wrong please retry or check the logs")
no traductions?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +                for model in self.env['ir.model'].search([])]
why not bellow the field definition?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +        string='Rendered XML Payload', compute="_compute_rendered_payload", readonly=True, store=True)
why stored ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +        string='JSON Params', compute='_compute_json_params', default='{}', store=True, readonly=True)
why stored ? and readonly is default ;-)

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +        string='Rendered JSON Payload', compute="_compute_rendered_payload", readonly=True, store=True)
same

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +    def _run_action_api_call(self, eval_context=None):
why eval_context ?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +                "Error: something went wrong please retry or check the logs")
traduction

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +            model = self.model_id.model
needed or directly in function, the less code we write the better

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +class IrActionsServerParamsLines(models.Model):
new file

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +class LogLines(models.Model):
new file

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/base_automation.py
> +    def test_api(self):
is it me or test_api is very similar to _run_action_api_call, maybe we should avoid duplicate logic

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +            return None
wut?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +                message_name = "Error"
message_name sounds like a selection field?

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/logs.py
> +    _name = 'logs'
I would try to come up with better name logs is too generic maybe 

also you can add menutitems for this fancy model

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/api.py
> +        default='get'
a default and a required ? choose one ;-)

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +                    ET.XML(server._render_template_qweb(server.resource_ref)))
I would call the _render_template_qweb only one and assign it to a variable

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +        self.ensure_one()
I think you are doing something wrong with this ensure one, check how it done for other _run_action_XXX

2022-07-14 20:54 UTC, tdetry commented on api_connector/api-module/models/ir_actions.py
> +            ET.XML(self._render_template_qweb()))
you have a nice computed field rendered_JSON_payload and you do not use it  ?

2022-08-10 14:42 UTC, tdetry requested changes
Great improvements! I see 2 missing features:
- I am not sur the response needs to be mapped to Odoo fields, can you. also provide the user with. the raw response so that he can play with? 
- I see the retry strategy :-) Can you also implement a scheduled action that will retry failed calls based on some condition? 

Then I see you coded some fancy functions is_xml, mapping,.. can you add tests for those?

2022-08-10 14:42 UTC, tdetry commented on README.md
> +Documentation: https://docs.google.com/document/d/13RRjkmujFDUbyTDfndR68rjL0gxGZCPTzdAurtwTfME/edit?usp=sharing
great!

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/api_request.py
> +class ApiRequest(models.Model):
this interface looks good !

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/api_log_lines.py
> +    _name = 'log.lines'
if you. do api.response.line, I would be consistant and do api.log.lines

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/base_automation.py
> +    mapping_error = fields.Boolean(string='Mapping Error')
I would add an space before fields definition

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/base_automation.py
> +        self.mapping_error = True if not res else False
wouldn't it be a good idea to display the "test" results" in a popup? you can check how they do it for the mail servers with the "test connections button" I do not think it. needs to go to the log ;)

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/base_automation.py
> +        api_request = self.env['api.request']
this. is good practice but as you use it only once, I would do:
```python
api_response = self.env['api.request'].make_api_call(api_config)
```

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/ir_actions.py
> +            return None
isn't this risky ?

2022-08-10 14:42 UTC, tdetry commented on api_connector/models/ir_actions.py
> +            _logger.warning("Error on send message")
traductions

2022-08-10 14:42 UTC, tdetry commented on api_connector/views/view_server_action_inherit.xml
> +                <page name="Help" string="Help" attrs="{'invisible':[('state','!=','api_call')]}" autofocus="autofocus">
I am not sure a new help page is needed, can we include this information above ? as they do for the "computed fields help?

2022-08-10 15:58 UTC, jefe-odoo requested changes
Good job. Please install a plugin to your IDE in order to format your code automatically and make sure you follow all guidelines from Odoo documentation.

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/__manifest__.py
> +        Link to project: https://www.odoo.com/web#id=2856455&menu_id=4720&cids=17&action=333&active_id=6182&model=project.task&view_type=form
When you have a document (user manual) about this dev, add it to README and here

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/__init__.py
> +from . import ir_actions
make sure  `__init__.py` files contains imports sorted by dependencies between them and in an alphabetical way

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_connection.py
> +    json_headers = fields.Text(
when a field is computed you don't need to specify `readonly` method because True is a default value for computed fields

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_connection.py
> +            api_connection.json_headers = self.env['ir.actions.server'].translate_o2m(
create a variable for `self.env['ir.actions.server']` before `for` statement then use it to execute `translate_o2m` method in the `for` statement

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_log_lines.py
> +    log_id = fields.Many2one('api.logs', string='API Logs', readonly=True)
if `log_id` is readonly then, should it be computed or when you set it?

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +from requests.adapters import HTTPAdapter
Follow [Odoo guideline](https://www.odoo.com/documentation/15.0/contributing/development/coding_guidelines.html#imports) about imports, apply it every where

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +    retry_strategy = Retry(
I think `retry_strategy` is a constant so use UPPER CASE

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +    # session.mount('https://', adapter)
Remove unused code

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +    def _get(self, api_config):
You can reduce code create a generic method that receives as a parameter the http verb (GET, POST, DELETE...)
and common parameters, I noticed the only difference is the method that is called.

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +        type_of_requests = {
Moreover you are mapping previous methods here.

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +            api_result.status_code = 400
Use HTTPStatus from http, take a look [here](https://docs.python.org/3/library/http.html)

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_request.py
> +            url = url + '/%s' % params[key]
don't use `+` to concatenate, use `join` or `%s`

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/api_response_lines.py
> +    def _compute_inner_fields(self):
change _compute by _onchange

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/ir_actions.py
> +        return [(model.model, model.name)
Use tuples of primitive data types instead of a singleton of a record set

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/ir_actions.py
> +                    server.rendered_JSON_payload = "No record to test"
Use a constant and  `_` to translate it

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/ir_actions.py
> +                'object': record or self.env[model].search([('id', "=", self._context.get('active_id', False))]),
Validate `self._context.get('active_id', False)` before query DB

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/models/ir_actions.py
> +        d = {t.tag: {} if t.attrib else None}
name variables according to their propose or why they were created

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/views/logs_menu_item.xml
> +                <field name="server_id" string="Action Name" filter_domain="['|', ('name', 'ilike', self),('ref', 'ilike', self)]"></field>
why did you use `self` for filter domain?

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/views/logs_menu_item.xml
> +                    <filter name="group_by_Api" string="Api" domain="[]" context="{'group_by': 'server_id'}" />
Remove domain if it doesn't have values

2022-08-10 15:58 UTC, jefe-odoo commented on api_connector/views/view_base_automation_inherit.xml
> +        <field name="mapping_error" invisible="1"></field>
Remove `</field>` and only use `<field name="mapping_error" invisible="1"/>`

2022-08-10 16:57 UTC, gecm-odoo commented on api_connector/models/__init__.py
> +from . import ir_actions
The `ir.actions` and `api_response_lines` need to be on top because the DB crashes if they are not but every other import is in alphabetical order.

2022-09-08 14:44 UTC, closed without merging