[ADD] code_survey: Moving code from personal repo
odoo-ps/psus-intern pull request #242
Opened 2022-07-22 17:28 UTC by yall-odoo

Moved code from personal repo to facilitate code preview

### Description

*Please include a summary of the change, the project task link and/or the ID.*

Link to task: [2856501](https://www.odoo.com/web#model=project.task&id=2856501)

### All Submissions:

* [x] My commit respects the [Odoo commit guideline](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#git)
* [x] My commit message respects the [commit template](https://github.com/odoo-ps/psbe-process/wiki/Commits-message-guidelines#template)
* [ ] I have used pre-commit
* [ ] The PR contains **only** my modification and **no other external** commit

### Sh/Runbot:

* [ ] The commits pass test and the branch is green
* [ ] Unit tests have been implemented / standard ones rewritten
* [ ] The Staging is ISO-Prod and will contain only this dev

### Upgrade:

* [ ] The data affected (*if any*) by the changes has been migrated

2022-07-22 21:12 UTC, emab-odoo requested changes
Great job, from what I cheked you just have some minor formatting issues to accomodate to the standard but other than that 👍

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_question.py
> +		for question in self:
Here you could make the code simpler, you could create a variable validation_required = False, and set it to true if the question.question_type == 'code_box', and after that write the record (question.validation_required = validation_required) that way you can avoid an else statement and makes it look much cleaner or you could do it all in one line if you so prefer: 
`question.validation_required = True if question.question_type == 'code_box' else False`

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_question.py
> +				question.validation_error_msg = _("The answer you entered is not valid.")
Same here!

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_question.py
> +			if not question.is_scored_question:
Same here

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_question.py
> +		# try:
Remember at the last review to not leave code commented :)

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_question_argument.py
> +
Remember 2 spaces 👍

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_user_input.py
> +
Two spaces 👍

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_user_input.py
> +    def _fetch_tests(self, question, isTest=False):
Try to use _ instead of cammel case for variables and parammeters, I love them too, but sadly the standard does not D:

2022-07-22 21:12 UTC, emab-odoo commented on code_survey/models/survey_user_input.py
> +        sol = Solution()
Why not just `return Soultion()`?

2022-07-25 13:45 UTC, yall-odoo commented on code_survey/models/survey_user_input.py
> +        sol = Solution()
True, I should return it directly

2022-07-25 22:07 UTC, daav-odoo commented on code_survey/models/survey_question.py
> +		# try:
Yep :)

2022-09-08 14:44 UTC, closed without merging