[ADD] Module to always show product's quatity in website
odoo-ps/psus-intern pull request #269
Opened 2022-08-04 21:09 UTC by ayhp-odoo

This module add functionality to always show the product quantity in the stock
in the product page of the eCommerce modifying the web controller to read the boolean field
and allows the user to still purchasing products even if the stock quantity is 0

Link to task: [2944858](https://www.odoo.com/web#id=2944858&cids=17&menu_id=4720&active_id=4532&model=project.task&view_type=form)

2022-08-04 21:43 UTC, tdetry reviewed
this development makes no sense in v15, right ?

2022-08-04 21:46 UTC, ayhp-odoo commented
> Yes, just the part of displaying it on the Website

2022-08-04 21:52 UTC, tdetry requested changes

2022-08-04 21:52 UTC, tdetry commented on always_show_qty/controllers/main.py
> +        return request.render("website_sale.product", self._prepare_product_values(product, category, search, **kwargs))
not needed

2022-08-04 21:52 UTC, tdetry commented on always_show_qty/views/product_template_website_from_view_inherit.xml
> +      <label for="show_availability" position="attributes">
add a small comment there to mention you remove the standard behovior from the settings

2022-08-04 21:52 UTC, tdetry commented on always_show_qty/views/templates.xml
> +  <template id="product_quantity" inherit_id="website_sale.product" active="True" name="Always Show Quatity" priority="20">
active not needed

2022-08-04 21:52 UTC, tdetry commented on always_show_qty/controllers/main.py
> +        return res
not needed

2022-08-04 21:52 UTC, tdetry commented on always_show_qty/controllers/main.py
> +        res = super(WebsiteSaleInherit, self)._prepare_product_values(
super() is enough

2022-08-04 22:32 UTC, ayhp-odoo commented on always_show_qty/controllers/main.py
> +        return request.render("website_sale.product", self._prepare_product_values(product, category, search, **kwargs))
Removed all the controller for do the functionality via view template

2022-08-05 17:56 UTC, jefe-odoo commented on always_show_qty/views/templates.xml
> +        <t t-else="" />
this else node can be removed

2022-09-08 14:44 UTC, closed without merging